### ISSUE TITLE
View Cards

### ISSUE THREAD

**Issue by mgerweck** [COSC-481W-Dodo/dodo-web#24]
As a student user of Dodo, I would like to view cards filtered by tags and by the cards I created.

**Tasks**
- [x] Add a view cards button to the navbar.
- [x] Add a view cards page
- [x] Add a section to select tags.
- [x] Display all cards associated with the selected tags.
- [x] Allow the option to filter by current users’ cards if they’re logged in.

**Acceptance Criteria**
- Users must be logged in to filter by their own cards.
- Users should be able to select tags to filter their card search.
- Only cards that have the selected tags should be displayed.
- Users should be able to navigate the view cards page by pressing the “view cards” button on the navbar.
