### ISSUE TITLE
Polish Navbar

### ISSUE THREAD

**Issue by mgerweck** [COSC-481W-Dodo/dodo-web#26]
As a user of Dodo, I would like the navbar to have a modern look and feel to match the rest of the website.

**Tasks**
- [x] Use icons where appropriate
- [x] Add Dodo logo
- [x] Change to an appropriate color

**Acceptance Criteria**
- The navbar has a modern look and feel.
- The icons make sense to their function
- The color matches the overall color scheme of the website.
