### ISSUE TITLE
Polish Home Page

### ISSUE THREAD

**Issue by mgerweck** [COSC-481W-Dodo/dodo-web#27]
As a user of Dodo, I would like to be greeted to a nice landing/home page when I first open the website.

**Tasks**
- [ ] Add appropriate text or images that gives a general idea of what the website is about
- [ ] Improve the styling of taking users to download the android app.
- [ ] (optional) Add anything else that feels appropriate to enhance the user experience.

**Acceptance Criteria**
- UI has visible improvement.
- UI has modern look and feel.
