### ISSUE TITLE
Polish Page Redirects

### ISSUE THREAD

**Issue by brandonijones** [COSC-481W-Dodo/dodo-web#28]
As a user of Dodo, I should not have access to pages when I am not authorized to be there.

**Tasks**
- [ ] Redirect if not logged in on the create-flashcards page
- [ ] Redirect if not logged in on the view/edit/settings page
- [ ] Redirect if already logged in on the login page
- [ ] Redirect if already logged in on the registration page

**Acceptance Criteria**
- Users get redirected to the login page if they are not authorized on the create-flashcards page or the view/edit/settings page
- Users get redirected to the home page if they are already logged in but navigate to the login or registration page.
