### ISSUE TITLE
Update tags collection schema

### ISSUE THREAD

**Issue by brandonijones** [COSC-481W-Dodo/dodo-web#29]
Currently, we have the document id's for the tags collection to be whatever the user enters in a tag field. However, there are some issues with that since Firebase does not allow certain characters as specified in the docs (https://cloud.google.com/firestore/docs/best-practices).

**Tasks**
- [ ] Modify user-entered string to create a readable document ID that meets Firebase requirements
- [ ] Add user-entered tag name to a name field in the tag document
- [ ] (?) Add user id to an array of authors (should make it easier to query tags only made by a given user)
- [ ] Handle duplicate tags 

**Acceptance Criteria**
- Tag documents have a readable ID.
- Modified user-entered string does not have special characters.
- Tags get successfully uploaded to the tags collection and the array of tags in the flashcard document.
